version: '3.8'

services:
  realmkit_mongo:
    image: mongo:latest
    hostname: realmkit_mongo
    container_name: realmkit_mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /tmp/dev/realmkit/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - realmkit_network
    restart: unless-stopped

networks:
  realmkit_network:
    driver: bridge
