app.static.data:
  battle:
    battle-duration: 100
    turn-duration: 10
  initial:
    stat:
      base:
        hull.max: 5.0
        shield.max: 0.0
        energy.max: 5.0
        attack: 1.0
        defense: 0.0
        speed: 1.0
        aggro: 1.0
      rate:
        shieldRegeneration: 0.0
        critical: 0.0
      multiplier:
        critical: 1.0
      progression:
        level: 1
        experience: 0
    resource:
      titanium: 1000
      crystal: 0
      dark-matter: 0
      anti-matter: 0
      purunhalium: 0
