app.static.data:
  battle-duration: 10
  turn-duration: 10
  resource:
    titanium: 1000
  ships:
    battle-war-ship-v1:
      name: WarShip V1.1
      stat:
        base:
          hull:
            max: 5.0
          energy:
            max: 5.0
          attack: 1.0
          speed: 1.0
          aggro: 1.0
        multiplier:
          critical: 1.0
        progression:
          level: 1
  items:
    drone-recovery-v1:
      name: Drone Recovery V1
      stat:
        base:
          hull:
            current: 10.0
