app.static.data:
  initial:
    stat:
      base:
        hull.max: 5.0
        shield.max: 0.0
        power: 1.0
        defense: 0.0
        speed: 1.0
      rate:
        shieldRegeneration: 0.0
        critical: 0.0
      multiplier:
        critical: 1.0
      progression:
        level: 1
        experience: 0
