app.static.data:
  battle-duration: 10
  resource:
    titanium: 1000
    crystal: 0
    dark-matter: 0
    anti-matter: 0
    purunhalium: 0
  battle-war-ship-v1:
    name: WarShip V1.1
    stat:
      base:
        hull.max: 5.0
        shield.max: 0.0
        energy.max: 5.0
        attack: 1.0
        defense: 0.0
        speed: 1.0
        aggro: 1.0
      rate:
        shield-regeneration: 0.0
        critical: 1.0
      multiplier:
        critical: 1.0
      progression:
        level: 1
        experience: 0
