[versions]
kotlin = "1.8.10"
dokka = "1.7.20"
sonarqube = "3.5.0.2730"
spring = "3.0.1"
spring-dependency = "1.1.0"
test-sets = "4.0.0"
spotless = "6.14.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
spring = { id = "org.springframework.boot", version.ref = "spring" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "spring-dependency" }
test-sets = { id = "org.unbroken-dome.test-sets", version.ref = "test-sets" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[bundles]
kotest = []
