[versions]
kotlin = "1.8.10"
kotlin-reflect = "1.2.41"
spring-boot = "3.0.2"
spring-dependency = "1.1.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "spring-dependency" }

[libraries]
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlin-stdlib-jkd8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8" }
spring-boot-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter" }
