name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  #      JOB: QODANA
  qodana:
    name: 'QODANA'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      #      CHECKOUT
      - name: 'Checkout Project'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #      QODANA
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: 'Qodana Upload Sarif'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

  #      JOB: COVERAGE
  coverage:
    name: 'COVERAGE'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      #      CHECKOUT
      - name: 'Checkout Project'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #      SETUP
      - name: 'Set up JDK 19'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19

      #      CACHE
      - name: 'Cache Gradle packages'
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: 'Cache SonarCloud packages'
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      #      BUILD
      - name: 'Build & Sonar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew check sonar --info

      #      UPLOAD RESULT
      - name: 'Codecov Upload Coverage'
        uses: codecov/codecov-action@v3
      - name: 'Detekt Upload Sarif'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/reports/detekt/detekt.sarif
