name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: 'COVERAGE'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      #      CHECKOUT
      - name: 'Checkout Project'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #      SETUP
      - name: 'Set up JDK 19'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19

      #      CACHE
      - name: 'Cache Gradle packages'
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      #      BUILD
      - name: 'Build and Test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build test --info
