name: Security

on: [push, pull_request]

jobs:
  #      JOB: GIT GUARDIAN
  git_guardian:
    name: 'GIT GUARDIAN'
    runs-on: ubuntu-latest
    steps:
      #      CHECKOUT
      - name: 'Checkout Project'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #      GIT GUARDIAN SCAN
      - name: 'GitGuardian'
        uses: GitGuardian/ggshield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}